name: Geotagger Frontend CI/CD

on: [ pull_request ]

env:
  NEXT_PUBLIC_API_URL: http://localhost:8000
  NEXT_PUBLIC_ENVIRONMENT: development
  NEXT_PUBLIC_BASE_URL: http://localhost:3000
  JWT_SECRET: secret


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm ci

      - name: Prettier format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck

      - name: Build
        run: npm run build